### ISSUE TITLE
Targeting pod, radar and RWR not working and purple square appearing

### ISSUE THREAD

**Issue by DatCrazyDelphox** [PapaJoesSoup/BDArmory#197]
When you open the targeting pod, no image appears, just a pink square.
And when you open the radar, no target appears even if the plane is in front of you

**Comment by gomker** [comment]
The issue you describe was fixed some time ago, this sounds like you are running an old version of BDA  - please delete the old version and make sure you are using the latest from 

https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.1 


When reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Comment by DatCrazyDelphox** [comment]
This is kinda strange, because im running with the 2.1.1stuff version...

**Comment by gomker** [comment]
I don't know what 2.1.1 version refers to, BDA nor KSP have those version numbers

**Comment by DatCrazyDelphox** [comment]
Sorry, my mistake...
Its BDAc v0.2.1.1. And yes, I already tried a clean install... The problem still persists...
Recently, I tweaked some of the config files and i made the RWR work again, but... No radar...

**Comment by jrodrigv** [comment]
We need a KSP.log file to understand the problem

**Comment by DatCrazyDelphox** [comment]
Sorry asking but, how do I get this type of log file?

**Comment by jrodrigv** [comment]
As soon KSP is executed, a KSP.log is generated inside the KSP installation
folder with all the traces.

**Comment by DatCrazyDelphox** [comment]
[a log.zip](https://github.com/PapaJoesSoup/BDArmory/files/1065293/a.log.zip)
here it is...
plus here are some images that shows the radar "functioning"
http://imgur.com/a/43rlV

**Comment by jrodrigv** [comment]
Problem found, you are running KSP with OpenGL. You should switch to
DirectX9 or DirectX11

**Comment by DatCrazyDelphox** [comment]
AH GAWD HOW COULD I FORGOT THIS!!!!!1!!!!!111!!!!
When I updated the ksp it was crashing everything so I tried to use opengl to see if it worked... Now those strange lag spikes are explained...

Thank ya :3
